// react/src/pages/PostList.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import PostItem from "../components/PostItem";

export default function PostList() {
  const [postList, setPostList] = useState([]);
  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts').then(res => res.json()).then(posts => {
        setPostList(posts);
    });
  }, []);
  function onDelete(post) {
    setPostList(postList.filter(p => p.id !== post.id));
  };
  return (
    <>
      <p>
        <Link to="/new" className="btn btn-success">
          Add new
        </Link>
      </p>
      <div>
        { postList.map(post => <PostItem key={post.id} post={post} onDelete={onDelete} />) }
      </div>
    </>
  );
}

// vue/src/pages/PostList.vue
<template>
    <p>
        <RouterLink to="/new" class="btn btn-success"> Add new </RouterLink>
    </p>
    <div>
        <PostItem v-for="post of postList" :key="post.id" :post="post" @delete="onDelete" />
    </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import PostItem from "../components/PostItem.vue";

const postList = ref([]);
onMounted(() => {
    fetch('https://jsonplaceholder.typicode.com/posts').then(res => res.json()).then(posts => {
        postList.value = posts;
    });
});

function onDelete(post) {
    postList.value = postList.value.filter(p => p.id !== post.id);
}
</script>

<style></style>
